# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

project 'RNMathView.xcworkspace'

target 'RNMathView' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  platform 'iOS'

  # Pods for RNMathView

  pod 'iosMath'

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

end
